### ISSUE TITLE
pos function generates 500 error for  Unicode Character 'RIGHT DOUBLE QUOTATION MARK' (U+201D)

### ISSUE THREAD

**Issue by taylorshaulis** [adsabs/montysolr#74]
If someone searches
pos(author:”Oort,+J”,2)
The query will fail

If they search
pos(author:"Oort,+J",2)
The query will succeed.

The only difference being the successful query is using double quote while the failing query is using right double quote.  Only considering this a bug because right double quote is accepted and understood for queries that do not use the POS function

2017-08-15 14:39:44.968 ERROR (qtp1190524793-290) [   x:collection1] o.a.s.s.HttpSolrCall null:java.lang.NumberFormatException: For input string: "J”"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at org.apache.solr.search.AqpFunctionQParser.parseInt(AqpFunctionQParser.java:131)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpAdsabsSubQueryProvider$15.parse(AqpAdsabsSubQueryProvider.java:349)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpSubQueryTreeBuilder.build(AqpSubQueryTreeBuilder.java:30)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpSubQueryTreeBuilder.build(AqpSubQueryTreeBuilder.java:13)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpFunctionQueryNodeBuilder.build(AqpFunctionQueryNodeBuilder.java:20)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpFunctionQueryNodeBuilder.build(AqpFunctionQueryNodeBuilder.java:10)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.processNode(QueryTreeBuilder.java:185)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.process(QueryTreeBuilder.java:124)
        at org.apache.lucene.queryparser.flexible.core.builders.QueryTreeBuilder.build(QueryTreeBuilder.java:217)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:69)
        at org.apache.lucene.queryparser.flexible.aqp.builders.AqpQueryTreeBuilder.build(AqpQueryTreeBuilder.java:35)
        at org.apache.lucene.queryparser.flexible.core.QueryParserHelper.parse(QueryParserHelper.java:253)
        at org.apache.lucene.queryparser.flexible.aqp.AqpQueryParser.parse(AqpQueryParser.java:228)
        at org.apache.solr.search.AqpAdsabsQParser.parse(AqpAdsabsQParser.java:285)
        at org.apache.solr.search.QParser.getQuery(QParser.java:140)
        at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:161)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:269)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:153)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2213)
        at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:303)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:518)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:748)

**Comment by spacemansteve** [comment]
The pos function gives a java.lang.NumberFormatException error when arguments are in the wrong order (pos(aff:"harvard",1) vs pos(1,aff:"harvard").  This results in a http 500 error, which seems very harsh.  Could we return an 400 error instead?
